export enum Modality {
  PART_TIME = 1,
  FULL_TIME = 2,
  FREE = 3,
  POSTULANTE_PLANILLA = 4,
  POSTULANTE_FREE = 5,
  PRACTICAS_PRE_PROFESIONALES = 6,
  PRACTICAS_PRO_PROFESIONALES = 7,
  POSTULANTE_PRACTICAS = 8,
}
